### ISSUE TITLE
when does this project start?

### ISSUE THREAD

**Issue by maravento** [phpvirtualbox-ng/phpvirtualbox#1]
I see you promote this fork, but I don't see any changes from the original version and the endless list of problems is still there. So when does this project start? thk

**Comment by BartekSz95** [comment]
> I see you promote this fork, but I don't see any changes from the original version and the endless list of problems is still there. So when does this project start? thk

I'm trying support this on my own repository. It's works with PHP8.1 and 8.2 actually and supporting new version of VBox 7.x.

https://github.com/BartekSz95/phpvirtualbox
